import { copilotToolRegistry } from "./registry";
import type { CopilotToolDescriptor } from "./types";

const BUILTIN_TOOLS: CopilotToolDescriptor[] = [
  { id: "search-book", area: "research", name: "Search Book", description: "Searches chapters, paragraphs, canon and research files inside the current book.", params: [{ name: "query", type: "string", description: "Search terms", required: true }], output: "Matching book paths and excerpts", prerequisites: ["book open"], requiresLlm: false, mutatesData: false, destructive: false, defaultEnabled: true, keywords: ["search", "find", "lookup", "cerca", "trova"], handlerId: "search-book" },
  { id: "switch-branch", area: "git", name: "Switch Branch", description: "Switches or creates a branch for the current book.", params: [{ name: "branchName", type: "string", description: "Target branch name", required: true }], output: "Branch-switch action", prerequisites: ["book open", "git token"], requiresLlm: false, mutatesData: true, destructive: false, defaultEnabled: true, keywords: ["branch", "switch branch", "create branch", "cambia branch", "vai sul branch"], handlerId: "switch-branch" },
  { id: "import-attachments", area: "utility", name: "Import Attachments", description: "Imports the current attachments into the book as paragraph/chapter/note/entity/script/draft source material.", params: [{ name: "attachments", type: "attachment[]", description: "Already uploaded attachments", required: true }], output: "Created or updated repo files", prerequisites: ["attachments"], requiresLlm: false, mutatesData: true, destructive: false, defaultEnabled: true, keywords: ["import", "attachment", "allega", "usa allegati"], handlerId: "import-attachments" },
  { id: "create-chapter", area: "chapter", name: "Create Chapter", description: "Creates a new chapter in the current book.", params: [{ name: "request", type: "string", description: "User request for the chapter", required: true }], output: "New chapter markdown file", prerequisites: ["book open"], requiresLlm: true, mutatesData: true, destructive: false, defaultEnabled: true, keywords: ["create chapter", "add chapter", "capitolo"], handlerId: "create-chapter" },
  { id: "create-paragraph", area: "paragraph", name: "Create Paragraph", description: "Creates a new paragraph in the current chapter.", params: [{ name: "request", type: "string", description: "User request for the paragraph", required: true }], output: "New paragraph markdown file", prerequisites: ["chapter open"], requiresLlm: true, mutatesData: true, destructive: false, defaultEnabled: true, keywords: ["create paragraph", "add paragraph", "paragrafo", "scene"], handlerId: "create-paragraph" },
  { id: "create-entity", area: "canon", name: "Create Canon Entity", description: "Creates a character, location, faction, item, secret or timeline event.", params: [{ name: "request", type: "string", description: "Entity creation request", required: true }], output: "New canon entity markdown file", prerequisites: ["book open"], requiresLlm: true, mutatesData: true, destructive: false, defaultEnabled: true, keywords: ["create character", "create location", "personaggio", "luogo", "fazione", "oggetto", "segreto"], handlerId: "create-entity" },
  { id: "create-script", area: "paragraph", name: "Create Script", description: "Creates a script workspace/scene for the current chapter or paragraph.", params: [{ name: "request", type: "string", description: "Script creation request", required: true }], output: "Script artifact", prerequisites: ["chapter or paragraph open"], requiresLlm: true, mutatesData: true, destructive: false, defaultEnabled: true, keywords: ["script", "scene script", "scaletta"], handlerId: "create-script" },
  { id: "create-draft", area: "paragraph", name: "Create Draft", description: "Creates a draft workspace for the current chapter or paragraph.", params: [{ name: "request", type: "string", description: "Draft creation request", required: true }], output: "Draft artifact", prerequisites: ["chapter or paragraph open"], requiresLlm: false, mutatesData: true, destructive: false, defaultEnabled: true, keywords: ["draft", "bozza"], handlerId: "create-draft" },
  { id: "update-plot", area: "book", name: "Update Plot", description: "Refreshes plot.md for the current book.", params: [{ name: "request", type: "string", description: "Plot update request", required: true }], output: "Updated plot.md", prerequisites: ["book open"], requiresLlm: true, mutatesData: true, destructive: false, defaultEnabled: true, keywords: ["plot", "aggiorna plot", "sync plot"], handlerId: "update-plot" },
  { id: "write-resume", area: "chapter", name: "Write Resume", description: "Writes or refreshes the chapter resume file.", params: [{ name: "request", type: "string", description: "Resume request", required: true }], output: "Updated chapter resume", prerequisites: ["chapter open"], requiresLlm: true, mutatesData: true, destructive: false, defaultEnabled: true, keywords: ["resume", "riassunto", "chapter recap"], handlerId: "write-resume" },
  { id: "write-evaluation", area: "chapter", name: "Write Evaluation", description: "Writes chapter or paragraph evaluations.", params: [{ name: "request", type: "string", description: "Evaluation request", required: true }], output: "Updated evaluation file", prerequisites: ["chapter or paragraph open"], requiresLlm: true, mutatesData: true, destructive: false, defaultEnabled: true, keywords: ["evaluation", "review file", "valutazione"], handlerId: "write-evaluation" },
  { id: "rewrite-current-paragraph", area: "paragraph", name: "Rewrite Current Paragraph", description: "Proposes a rewrite of the current paragraph body.", params: [{ name: "request", type: "string", description: "Rewrite request", required: true }], output: "Proposed paragraph rewrite", prerequisites: ["paragraph open"], requiresLlm: true, mutatesData: false, destructive: false, defaultEnabled: true, keywords: ["rewrite", "revise", "fix paragraph", "riscrivi", "migliora"], handlerId: "rewrite-paragraph" },
  { id: "create-note", area: "notes", name: "Create Context Note", description: "Creates or appends a contextual note for the current route.", params: [{ name: "request", type: "string", description: "Note request", required: true }], output: "Updated note file", prerequisites: ["book open"], requiresLlm: true, mutatesData: true, destructive: false, defaultEnabled: true, keywords: ["note", "notes", "appunto", "memo"], handlerId: "create-note" },
  { id: "review-context", area: "utility", name: "Review Context", description: "Editorial review of the current loaded context.", params: [{ name: "request", type: "string", description: "Review request", required: true }], output: "Review response", prerequisites: ["context loaded"], requiresLlm: true, mutatesData: false, destructive: false, defaultEnabled: true, keywords: ["review", "critique", "feedback", "valuta"], handlerId: "review-context" },
  { id: "summarize-context", area: "utility", name: "Summarize Context", description: "Summarizes the current loaded book context.", params: [{ name: "request", type: "string", description: "Summary request", required: true }], output: "Summary response", prerequisites: ["context loaded"], requiresLlm: true, mutatesData: false, destructive: false, defaultEnabled: true, keywords: ["summary", "summarize", "riassunto", "overview"], handlerId: "summarize-context" },
  { id: "answer-from-context", area: "utility", name: "Answer From Context", description: "General contextual copilot answer from loaded repository files.", params: [{ name: "request", type: "string", description: "User request", required: true }], output: "Answer", prerequisites: ["context loaded"], requiresLlm: true, mutatesData: false, destructive: false, defaultEnabled: true, keywords: [], handlerId: "answer-from-context" },
  { id: "deep-research", area: "research", name: "Deep Research", description: "Runs deep research with intent-aware provider routing and saves a research document.", params: [{ name: "query", type: "string", description: "Research query", required: true }], output: "Saved research markdown", prerequisites: ["book open"], requiresLlm: true, mutatesData: true, destructive: false, defaultEnabled: true, keywords: ["deep research", "research", "ricerca approfondita"], handlerId: "deep-research" },
  { id: "create-from-research", area: "research", name: "Create From Research", description: "Creates a canon entity starting from an existing research file.", params: [{ name: "research", type: "string", description: "Research reference", required: true }], output: "New canon entity", prerequisites: ["book open", "research available"], requiresLlm: true, mutatesData: true, destructive: false, defaultEnabled: true, keywords: ["create from research", "partendo da questa ricerca"], handlerId: "create-from-research" },
  { id: "read-current-page", area: "audio", name: "Read Current Page", description: "Reads the current page or current text aloud via TTS without sending it to an LLM.", params: [], output: "Spoken audio", prerequisites: ["current page"], requiresLlm: false, mutatesData: false, destructive: false, defaultEnabled: true, keywords: ["read this", "leggimi", "read aloud", "leggi"], handlerId: "read-current-page" },
  { id: "open-reader", area: "navigation", name: "Open Reader", description: "Navigates to the reader for the current book.", params: [], output: "Navigation", prerequisites: ["book open"], requiresLlm: false, mutatesData: false, destructive: false, defaultEnabled: true, keywords: ["open reader", "apri reader"], handlerId: "open-reader" },
  { id: "delete-current-note", area: "notes", name: "Delete Current Note", description: "Deletes the currently open note.", params: [], output: "Deleted note", prerequisites: ["note open"], requiresLlm: false, mutatesData: true, destructive: true, defaultEnabled: false, keywords: ["delete note", "elimina nota"], handlerId: "delete-current-note" },
  { id: "delete-current-paragraph", area: "paragraph", name: "Delete Current Paragraph", description: "Deletes the current paragraph and renumbers its companion files.", params: [], output: "Deleted paragraph", prerequisites: ["paragraph open"], requiresLlm: false, mutatesData: true, destructive: true, defaultEnabled: false, keywords: ["delete paragraph", "elimina paragrafo"], handlerId: "delete-current-paragraph" },
  { id: "delete-current-entity", area: "canon", name: "Delete Current Canon Entity", description: "Deletes the currently open canon entity.", params: [], output: "Deleted entity", prerequisites: ["canon entity open"], requiresLlm: false, mutatesData: true, destructive: true, defaultEnabled: false, keywords: ["delete character", "delete entity", "elimina personaggio", "elimina entità"], handlerId: "delete-current-entity" },
];

let registered = false;

export function ensureBuiltinCopilotToolsRegistered() {
  if (registered) return;
  copilotToolRegistry.registerMany(BUILTIN_TOOLS);
  registered = true;
}
