import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import fg from "fast-glob";

const workspaceRoot = fileURLToPath(new URL("../../..", import.meta.url));
const siteRoot = fileURLToPath(new URL("..", import.meta.url));
const outputPath = path.join(siteRoot, "src", "lib", "generated-docs.ts");

const groupLabels = {
  overview: "Overview",
  reference: "Reference",
  packages: "Packages",
};

async function main() {
  const [referenceDocs, packageReadmes] = await Promise.all([
    fg("docs/**/*.md", { cwd: workspaceRoot, onlyFiles: true }),
    fg("packages/*/README.md", { cwd: workspaceRoot, onlyFiles: true }),
  ]);

  const sources = [
    {
      sourcePath: "README.md",
      group: "overview",
      slug: "framework",
      fallbackTitle: "Framework Overview",
      order: 0,
    },
    {
      sourcePath: "AGENTS.md",
      group: "overview",
      slug: "agent-rules",
      fallbackTitle: "Agent Rules",
      order: 1,
    },
    ...referenceDocs.sort().map((sourcePath, index) => ({
      sourcePath,
      group: "reference",
      slug: path.basename(sourcePath, ".md"),
      fallbackTitle: humanize(path.basename(sourcePath, ".md")),
      order: 100 + index,
    })),
    ...packageReadmes.sort().map((sourcePath, index) => {
      const packageName = sourcePath.split("/")[1];
      return {
        sourcePath,
        group: "packages",
        slug: packageName,
        fallbackTitle: packageTitle(packageName),
        order: 200 + index,
      };
    }),
  ];

  const docs = await Promise.all(
    sources.map(async (source) => {
      const absolutePath = path.join(workspaceRoot, source.sourcePath);
      const markdown = await readFile(absolutePath, "utf8");
      return {
        title: extractTitle(markdown) ?? source.fallbackTitle,
        href: `/docs/${source.slug}`,
        slug: source.slug,
        group: source.group,
        groupLabel: groupLabels[source.group],
        sourcePath: source.sourcePath,
        summary: extractSummary(markdown),
        markdown,
        order: source.order,
      };
    }),
  );

  const mcpTools = await loadToolEntries();
  const payload = `/* eslint-disable */\n` +
    `// This file is generated by scripts/generate-docs.mjs. Do not edit it manually.\n\n` +
    `export type DocGroup = "overview" | "reference" | "packages";\n\n` +
    `export type DocEntry = {\n` +
    `  title: string;\n` +
    `  href: string;\n` +
    `  slug: string;\n` +
    `  group: DocGroup;\n` +
    `  groupLabel: string;\n` +
    `  sourcePath: string;\n` +
    `  summary: string;\n` +
    `  markdown: string;\n` +
    `};\n\n` +
    `export type ToolEntry = {\n` +
    `  name: string;\n` +
    `  description: string;\n` +
    `  surface: "local" | "public";\n` +
    `  category: string;\n` +
    `};\n\n` +
    `export const docEntries: DocEntry[] = ${JSON.stringify(
      docs
        .sort((left, right) => left.order - right.order)
        .map(({ order: _order, ...entry }) => entry),
      null,
      2,
    )};\n\n` +
    `export const mcpTools: ToolEntry[] = ${JSON.stringify(mcpTools, null, 2)};\n`;

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, payload, "utf8");
}

async function loadToolEntries() {
  const localTools = await parseToolFile(
    path.join(workspaceRoot, "packages", "mcp-server", "src", "index.ts"),
    "local",
  );
  const publicTools = await parseToolFile(
    path.join(workspaceRoot, "packages", "mcp-server", "src", "public-http-server.ts"),
    "public",
  );
  return [...localTools, ...publicTools].sort((left, right) =>
    left.name.localeCompare(right.name),
  );
}

async function parseToolFile(filePath, surface) {
  const source = await readFile(filePath, "utf8");
  const matches = source.matchAll(/server\.tool\(\s*"([^"]+)"\s*,\s*"([\s\S]*?)"\s*,/g);
  const tools = [];
  for (const match of matches) {
    const name = match[1];
    const description = match[2].replace(/\s+/g, " ").trim();
    tools.push({ name, description, surface, category: toolCategory(name) });
  }
  return tools;
}

function packageTitle(value) {
  switch (value) {
    case "core":
      return "Core Package";
    case "mcp-server":
      return "MCP Server Package";
    case "create-narrarium-book":
      return "Create Book Package";
    case "astro-reader":
      return "Astro Reader Package";
    default:
      return humanize(value);
  }
}

function extractTitle(markdown) {
  const match = markdown.match(/^#\s+(.+)$/m);
  return match?.[1]?.trim() ?? null;
}

function extractSummary(markdown) {
  const cleaned = markdown
    .replace(/^---[\s\S]*?---\s*/m, "")
    .split(/\n\n+/)
    .map((block) => block.trim())
    .find(
      (block) =>
        block &&
        !block.startsWith("#") &&
        !block.startsWith("```") &&
        !block.startsWith("-") &&
        !block.startsWith("1."),
    );
  return cleaned ? cleaned.replace(/\s+/g, " ") : "Documentation entry.";
}

function humanize(value) {
  return value
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function toolCategory(name) {
  if (name === "setup_framework" || name === "repository_spec" || name.startsWith("wikipedia_")) {
    return "Setup and research";
  }
  if (name.startsWith("start_wizard") || name.startsWith("wizard_") || name.endsWith("_wizard")) {
    return "Guided flows";
  }
  if (name === "init_book_repo" || name.startsWith("create_") || name.startsWith("register_") || name.startsWith("generate_")) {
    return "Creation and assets";
  }
  if (name.startsWith("update_") || name.startsWith("rename_")) {
    return "Updates and renames";
  }
  if (name.startsWith("search_") || name.startsWith("list_")) {
    return "Search and continuity";
  }
  if (name.startsWith("sync_") || name.startsWith("evaluate_") || name.startsWith("validate_") || name.startsWith("export_")) {
    return "Maintenance and output";
  }
  return "Other";
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
