export {
  AzureDevOpsRemoteProvider,
  type AzureDevOpsRemoteProviderOptions,
  BookManager,
  type BookManagerOptions,
  GitHubRemoteProvider,
  type GitHubRemoteProviderOptions,
  InMemoryBookProfileStore,
  LocalStorageBookProfileStore,
  NarrariumBookWorkspace,
  buildNarrariumBookSnapshot,
  classifyNarrariumDocumentKind,
  createEmptyBookSnapshot,
  normalizeNarrariumDocumentPath,
  parseNarrariumMarkdownDocument,
  serializeNarrariumDocument,
} from "narrarium";

export type {
  BookConnectionProfileResponse,
  BookGitStateResponse,
  CommitBookChangeRequest,
  CommitBookRequest,
  CreateAzureDevOpsProfileRequest,
  CreateGitHubProfileRequest,
  NoteMutationRequest,
  NarrariumApiClientOptions,
} from "./api-client.js";

export { NarrariumApiClient } from "./api-client.js";

export type {
  AzureDevOpsBookConnectionProfile,
  BaseBookConnectionProfile,
  BookCommitRequest,
  BookConnectionProfile,
  BookConnectionProfileStore,
  ContextFrontmatter,
  BookProviderKind,
  BookPushResult,
  ChapterDocumentInput,
  ChapterDocumentLocator,
  CharacterDocumentInput,
  CharacterDocumentLocator,
  CreateAzureDevOpsBookConnectionProfileInput,
  CreateEmptyBookSnapshotInput,
  CreateGitHubBookConnectionProfileInput,
  GitHubBookConnectionProfile,
  LocalStorageBookProfileStoreOptions,
  NoteFrontmatter,
  NarrariumAnyDocument,
  NarrariumBookSnapshot,
  NarrariumChapterSnapshot,
  NarrariumContextDocument,
  NarrariumDocument,
  NarrariumDocumentKind,
  NarrariumDraftChapterSnapshot,
  NarrariumNoteDocument,
  NarrariumRemoteProvider,
  NarrariumRemoteProviderCommitArgs,
  NarrariumRemoteProviderLoadArgs,
  NarrariumDocumentPatch,
  ParagraphDocumentInput,
  ParagraphDocumentLocator,
  NarrariumWorkspaceChange,
  NarrariumWorkspaceDeleteChange,
  NarrariumWorkspaceUpsertChange,
  StringKeyValueStore,
} from "narrarium";
